### ISSUE TITLE
Helsinki-NLP/opus-mt-jap-en not translating correctly 

### ISSUE THREAD

**Issue by ravi111282** [Helsinki-NLP/OPUS-MT-train#56]
Background: Using the MarianMTmodel and MarianTokenizer from Huggingface for translating Japanese text to english 
Issue: The Helsinki-NLP/opus-mt-jap-en is translating incorrectly (completely)
Example :Input Sentence :
日本の東京へようこそ！ (Welcome to Tokyo  Japan !)

Output of the Helsinki-NLP/opus-mt-jap-en model : For even as we go toward the east,

Is this a known issue and is there a way to improve the translation quality?

**Comment by jorgtied** [comment]
I don't know. Could you try the latest model from https://github.com/Helsinki-NLP/Tatoeba-Challenge/tree/master/models/jpn-eng (https://object.pouta.csc.fi/Tatoeba-MT-models/jpn-eng/opus-2021-02-18.zip) with plain MarianNMT?

**Comment by torebre** [comment]
I am also having problems with the Japanese translations. If I try with plain MarianNMT I still get problems, here are some examples:

`echo "彼らは夫婦になった。" | ./marian-decoder -m opus-2021-02-18/opus.spm32k-spm32k.transformer.model1.npz.best-perplexity.npz -v opus.spm32k-spm32k.vocab.yml opus-2021-02-18/opus.spm32k-spm32k.vocab.yml --beam-size 6 --normalize 1 --word-penalty 0 --mini-batch 1 --maxi-batch 1 --maxi-batch-sort src --cpu-threads 2`
Best translation 0 : ▁I ' m ▁sorry .
"彼らは夫婦になった。" could be translated as "they became husband and wife". This is one of the sentences from the test set (https://object.pouta.csc.fi/Tatoeba-MT-models/jpn-eng/opus-2020-06-17.test.txt). 
When I look at the test set in a browser, the Japanese text is garbled by the way. It looks like the encoding is not set correctly, so that UTF-8 characters are interpreted as a single character encoding.

`echo "先生の動画" | ./marian-decoder -m opus-2021-02-18/opus.spm32k-spm32k.transformer.model1.npz.best-perplexity.npz -v opus-2021-02-18/opus.spm32k-spm32k.vocab.yml opus-2021-02-18/opus.spm32k-spm32k.vocab.yml --beam-size 6 --normalize 1 --word-penalty 0 --mini-batch 1 --maxi-batch 1 --maxi-batch-sort src --cpu-threads 2`
Best translation 0 : ▁I ' m ▁sorry .
"先生の動画" could be translated as "teacher's video"

`echo "私" | ./marian-decoder -m opus-2021-02-18/opus.spm32k-spm32k.transformer.model1.npz.best-perplexity.npz -v opus.spm32k-spm32k.vocab.yml opus-2021-02-18/opus.spm32k-spm32k.vocab.yml --beam-size 6 --normalize 1 --word-penalty 0 --mini-batch 1 --maxi-batch 1 --maxi-batch-sort src --cpu-threads 2`
Best translation 0 : ▁I ▁am .
"私" means "I", so this is a bit closer to a correct translation.

The Japanese to English translations in the application on HuggingFace work fine (https://huggingface.co/spaces/Helsinki-NLP/opus-translate). Are the same models used there?

The translations from the English to Japanese are also not correct when I try:

`echo "Book" | ./marian-decoder -m opus-2020-01-08-en-jap/opus.spm32k-spm32k.transformer-align.model1.npz.best-perplexity.npz -v opus-2020-01-08-en-jap/opus.spm32k-spm32k.vocab.yml opus-2020-01-08-en-jap/opus.spm32k-spm32k.vocab.yml --beam-size 6 --normalize 1 --word-penalty 0 --mini-batch 1 --maxi-batch 1 --maxi-batch-sort src --cpu-threads 2`
Best translation 0 : ▁ マ グ ブ
"マ グ ブ" does not mean book.

Other languages work better, here is an example from the English to German model: 
`echo "This is a test" | ./marian-decoder -m opus-2020-02-26/opus.spm32k-spm32k.transformer-align.model1.npz.best-perplexity.npz -v opus-2020-02-26/opus.spm32k-spm32k.vocab.yml opus-2020-02-26/opus.spm32k-spm32k.vocab.yml --beam-size 6 --normalize 1 --word-penalty 0 --mini-batch 1 --maxi-batch 1 --maxi-batch-sort src --cpu-threads 2`
Best translation 0 : ▁Dies ▁ist ▁ein ▁Test

Any idea to what I am doing wrong when using the Japanese language models?

**Comment by torebre** [comment]
In case someone else made the same mistake, here is what I did wrong when using MarianNMT: I didn't run spm_encode, or spm_decode. When I did that the translations are correct:

`echo "先生の動画" | ./spm_encode --model opus-2021-02-18/source.spm | ./marian-decoder -m opus-2021-02-18/opus.spm32k-spm32k.transformer.model1.npz.best-perplexity.npz -v opus-2021-02-18/opus.spm32k-spm32k.vocab.yml opus-2021-02-18/opus.spm32k-spm32k.vocab.yml --beam-size 6 --normalize 1 --word-penalty 0 --mini-batch 1 --maxi-batch 1 --maxi-batch-sort src --cpu-threads 2 | ./spm_decode --model opus-2021-02-18/target.spm`

The teacher's video.
